version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
  json:
    format: "%(asctime)s %(name)s %(levelname)s %(filename)s %(lineno)d %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/multi_agent.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  query_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/queries.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  '':  # root logger
    level: INFO
    handlers:
      - console
      - file
      - error_file
    propagate: true

  src:
    level: INFO
    handlers:
      - console
      - file
    propagate: false

  src.agents:
    level: INFO
    handlers:
      - console
      - file
    propagate: false

  src.core:
    level: INFO
    handlers:
      - console
      - file
    propagate: false
  
  src.database:
    level: INFO
    handlers:
      - console
      - file
    propagate: false

  src.interfaces:
    level: INFO
    handlers:
      - console
      - file
    propagate: false

  query_logger:
    level: INFO
    handlers:
      - query_file
    propagate: false